export const DeveloperApiErrorCodes = {
    INVALID_API_KEY: "INVALID_API_KEY",
    API_KEY_DISABLED: "API_KEY_DISABLED",
    API_KEY_EXPIRED: "API_KEY_EXPIRED",

    TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
    TENANT_NOT_ALLOWED: "TENANT_NOT_ALLOWED",

    SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",

    SYSTEM_NOT_FOUND: "SYSTEM_NOT_FOUND",
    API_ACCESS_DENIED: "API_ACCESS_DENIED",

    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    INVALID_RESOURCE: "INVALID_RESOURCE",
    RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
    TENANT_SLUG_REQUIRED: "TENANT_SLUG_REQUIRED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type DeveloperApiErrorCode =
    typeof DeveloperApiErrorCodes[keyof typeof DeveloperApiErrorCodes];