-- Superseded by 20260825130000_harden_kashier_provisioning.sql.
-- Kept as a no-op to preserve migration history after the original hardening
-- migration was replaced with the consolidated implementation.
