-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  avatar_url text,
  country text,
  city text,
  preferred_language text DEFAULT 'ar'::text,
  is_verified boolean DEFAULT false,
  sex USER-DEFINED NOT NULL DEFAULT 'male'::user_sex,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text UNIQUE,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.systems (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL CHECK (char_length(description) <= 250),
  owner_id uuid NOT NULL,
  currency text DEFAULT 'EGP'::text,
  status USER-DEFINED DEFAULT 'PENDING'::global_status,
  category text,
  icon_url text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  starter_price numeric NOT NULL DEFAULT 0,
  pro_price numeric NOT NULL DEFAULT 0,
  business_price numeric NOT NULL DEFAULT 0,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  reseller_price numeric NOT NULL DEFAULT 0,
  exclusive_price numeric NOT NULL DEFAULT 0,
  status_reason text CHECK (status_reason IS NULL OR char_length(status_reason) <= 500),
  readme text CHECK (readme IS NULL OR char_length(readme) <= 30000),
  pending_readme text CHECK (pending_readme IS NULL OR char_length(pending_readme) <= 30000),
  pending_readme_submitted_at timestamp with time zone,
  pending_readme_submitted_by uuid,
  image_url text,
  CONSTRAINT systems_pkey PRIMARY KEY (id),
  CONSTRAINT systems_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT systems_pending_readme_submitted_by_fkey FOREIGN KEY (pending_readme_submitted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  system_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  subdomain text,
  status USER-DEFINED DEFAULT 'PENDING'::global_status,
  logo_url text,
  primary_color text,
  email text NOT NULL,
  phone text,
  country text,
  city text,
  address text,
  timezone text DEFAULT 'Africa/Cairo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subscription_id uuid UNIQUE,
  CONSTRAINT tenants_pkey PRIMARY KEY (id),
  CONSTRAINT tenants_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id),
  CONSTRAINT tenants_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT tenants_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.memberships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  current_tenant_id uuid,
  role USER-DEFINED NOT NULL,
  permissions ARRAY DEFAULT '{}'::text[],
  status USER-DEFINED DEFAULT 'ACTIVE'::global_status,
  invited_by uuid,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT memberships_pkey PRIMARY KEY (id),
  CONSTRAINT memberships_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT memberships_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL,
  tenant_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  invited_by uuid NOT NULL,
  status USER-DEFINED DEFAULT 'PENDING'::invitation_status,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  message text,
  permissions json,
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  system_id uuid NOT NULL,
  plan_name text NOT NULL,
  billing_interval USER-DEFINED NOT NULL,
  price numeric NOT NULL,
  currency text DEFAULT 'EGP'::text,
  status USER-DEFINED DEFAULT 'TRIAL'::subscription_status,
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  end_date timestamp with time zone,
  trial_end_date timestamp with time zone,
  auto_renew boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  license_type text DEFAULT 'SUBSCRIPTION'::text,
  profile_id uuid,
  order_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id),
  CONSTRAINT subscriptions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT subscriptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  system_id uuid NOT NULL,
  subscription_id uuid,
  profile_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'EGP'::text,
  status USER-DEFINED DEFAULT 'PENDING'::order_status,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan text,
  license_type text NOT NULL,
  coupon_id uuid,
  original_amount numeric NOT NULL DEFAULT 0,
  discount_amount numeric NOT NULL DEFAULT 0,
  discount_percentage numeric CHECK (discount_percentage IS NULL OR discount_percentage >= 1::numeric AND discount_percentage <= 100::numeric),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id),
  CONSTRAINT orders_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT orders_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  provider USER-DEFINED NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'EGP'::text,
  status USER-DEFINED DEFAULT 'PENDING'::payment_status,
  transaction_ref text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  provider_reference text UNIQUE,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.developer_api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  system_id uuid NOT NULL,
  key_hash text NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  encrypted_key text,
  CONSTRAINT developer_api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT fk_developer_api_keys_system FOREIGN KEY (system_id) REFERENCES public.systems(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  is_generated boolean NOT NULL DEFAULT false,
  system_id uuid,
  created_by uuid NOT NULL,
  discount_type text NOT NULL CHECK (discount_type = 'PERCENT'::text),
  discount_value numeric NOT NULL CHECK (discount_value >= 1::numeric AND discount_value <= 100::numeric),
  max_discount numeric CHECK (max_discount IS NULL),
  license_type text CHECK (license_type = ANY (ARRAY['SUBSCRIPTION'::text, 'RESELLER'::text, 'EXCLUSIVE'::text])),
  plan text CHECK (plan = ANY (ARRAY['STARTER'::text, 'PRO'::text, 'BUSINESS'::text])),
  min_order_amount numeric NOT NULL DEFAULT 0,
  max_uses integer,
  max_uses_per_user integer NOT NULL DEFAULT 1,
  used_count integer NOT NULL DEFAULT 0,
  one_use_per_system boolean NOT NULL DEFAULT true,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id),
  CONSTRAINT coupons_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.coupon_usages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coupon_id uuid NOT NULL,
  order_id uuid NOT NULL,
  system_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  used_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT coupon_usages_pkey PRIMARY KEY (id),
  CONSTRAINT coupon_usages_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT coupon_usages_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT coupon_usages_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id),
  CONSTRAINT coupon_usages_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name_en text NOT NULL,
  name_ar text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'SUPER_ADMIN'::system_role,
  created_at timestamp with time zone DEFAULT now(),
  audit_logs_last_viewed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_staff_pkey PRIMARY KEY (id),
  CONSTRAINT platform_staff_user_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  tenant_id uuid,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);